name: Publish AAR to GitHub Packages
on:
  push:
    paths:
      - '**/*.aar'   # Specify the path pattern of AAR files

jobs:
  publish:
    name: Publish AAR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Publish AAR to GitHub Packages
        run: |
          echo "//maven.pkg.github.com/JuTaK97/android-rn-prebuilt/:username=JuTaK97" > ~/.npmrc
          echo "//maven.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
          for aarFile in $(find . -name "*.aar"); do
            FILENAME=$(basename "$aarFile")
            ARTIFACT_ID="${FILENAME%.*}"
            mvn deploy:deploy-file -Dfile="$aarFile" -DrepositoryId=github -Durl=https://maven.pkg.github.com/JuTaK97/android-rn-prebuilt -DgroupId=com.github.JuTaK97.androidrnprebuilt -DartifactId="$ARTIFACT_ID" -Dversion=1.0.0 -Dpackaging=aar
          done